# Default values for helm-oci-django-atp
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# AutonmousDB variables
#
# name assigned to autonomousdatabases resource (Required)
name: autodbtest501
# OCID of compartment to create the autonomousdatabase (Required)
compartmentId: 
# Name assigned to the autonomousdatabase in OCI (Required)
DBName: autodbtest501
# OLTP or DW (Required)
dbWorkload: OLTP
#  True if the database is on dedicated Exadata infrastructure (defaults to false)
isDedicated: false
# A valid Oracle Database version for Autonomous Database (Not Required)
dbVersion: 
# The size, in terabytes, of the data volume that will be created and attached to the database. This storage can later be scaled up if needed (Required)
dataStorageSizeInTBs: 2
# The number of OCPU cores (Required)
cpuCoreCount: 2
# indicates if auto scaling is enabled for the Autonomous Database OCPU core count (Defaukts to false)
isAutoScalingEnabled: false
# Indicates if this is an Always Free resource. (Defaults to false)
isFreeTier: false
# LICENSE_INCLUDED or BRING_YOUR_OWN_LICENSE ( Defaults to ICENSE_INCLUDED)
licenseModel: 
wallet:
  # walletName (Required)
  walletName: autodbwallet
  walletPassword:
    secret:
      # secretName (Required)
      secretName: walletpassword
adminPassword:
  secret:
    # secretName (Required)
    secretName: dbpassword
freeformTags:
definedTags:
# Can be set during Helm installation (best practice is not to set passwords in this file)
dbPassword: 
walletPassword: 


# Django deployment variables
#
replicaCount: 1
# (Required)
initContainerImage: 'chiphwang/checkautodb:2.1'
# (Required)
containerImage: 'chiphwang/django_atp:1.6'
# location to write wallet files (Required) Do not change for this Helm chart
secretPath: '/wallet/'

# specify service level for Autonomous . This a combination of the name of Autonomous DB defined in in the na,es field above
#  + _high , _medium, _low  for service level
# example 'autodbtest501_high'
dbServiceLevel: 


