apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.adminPassword.secret.secretName}}
type: Opaque
data:
  password: {{ .Values.dbPassword| required "database password is required" | b64enc | quote }}
