apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.wallet.walletPassword.secret.secretName}}
type: Opaque
data:
  walletPassword: {{ .Values.walletPassword | required "Wallet password is required" | b64enc | quote }}
